### ISSUE TITLE
bruegel ?

### ISSUE THREAD

**Issue by kapouer** [fintechdev/Milieu#4]
I wonder what's the painting - which i find very pretty, and probably a good model for puzzles :)

**Comment by RobertWHurst** [comment]
I think it's by Charles Euphrasie Kuwasseg.
Absolutely. I can totally see this as a jigsaw puzzle 😄

**Comment by kapouer** [comment]
Wonderful painter ! Never heard of him, and it's not easy to find books on him.
Thank you for that :)

**Comment by RobertWHurst** [comment]
No problem! Cheers 🍻
